# Generated by Django 5.0.7 on 2024-08-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelledDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wasCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
