# Generated by Django 5.0.7 on 2024-07-30 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('displayName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isActive', models.BooleanField(default=True)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('expireDate', models.DateField(blank=True, null=True)),
                ('categoryId', models.IntegerField()),
                ('availableQty', models.SmallIntegerField()),
                ('lastModificationDate', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('deletedDate', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
            ],
        ),
    ]
