# Generated by Django 5.0.7 on 2024-07-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryId',
        ),
    ]
